name: partypassui
description: A Flutter-based app for PartyPass with subscription and QR code management.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.3

  # HTTP Requests
  http: ^0.15.0

  # QR Code Scanning
  qr_code_scanner: ^0.5.2

  # Shared Preferences for Session Management
  shared_preferences: ^2.0.18

  # Flutter Widgets and Animations
  flutter_svg: ^1.0.0

  # Local Notifications (Optional)
  flutter_local_notifications: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/companylogo.png
    - assets/images/splashscreenlogo.png
    - assets/images/placeholder.png
    - assets/icons/gmail.png
    - assets/icons/facebook.png
    - assets/icons/x.png

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
